azure:
  client:
    clientId: 616f335f-0197-47e9-bc7f-21531db1969d
    clientSecret: 
    accessTokenUri: https://login.windows.net/6f844683-d7cd-4c64-8d8b-24b8dd78be1b/oauth2/token
    userAuthorizationUri: https://login.windows.net/6f844683-d7cd-4c64-8d8b-24b8dd78be1b/oauth2/authorize
    tokenName: access_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.microsoftonline.com/me
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG